import "./globals.css";
import Header from "./Component/header";
import Providers from "./Providers";
import Navbar from "./Component/Navbar";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* HEADER */}
          <Header />
          {/* NAVBAR */}
          <Navbar />
          {/* SEARCH ICON */}

          {children}
        </Providers>
      </body>
    </html>
  );
}
